version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: imrsac_db
      MYSQL_ROOT_PASSWORD: Orion@99
      MYSQL_USER: dilss
      MYSQL_PASSWORD: Orion@99
      
