version: '3.1'

services:
  hmi:
    build: ./hmi
    container_name: hmi
    depends_on:
      - backend
    ports:
      - '4200:4200'

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - '8080:8080'
    
  db:
    image: mysql
    container_name: db
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  data:
      
