services:
  hmi:
    build: ./hmi
    container_name: hmi
    depends_on:
      - backend
    ports:
      - '4200:4200'

  backend:
    build:
      context: ./backend/app
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: backend
    depends_on:
      - db
    ports:
      - '8080:8080'

  keycloak:
    image: keycloak/keycloak
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db:3306/keycloak_db
      KC_DB_USERNAME: dilss
      KC_DB_PASSWORD: Orion@99

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8081:8080'
    command: start-dev
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  data:
