include:
  - ./chirpstack-docker/docker-compose.yml

services:
  hmi:
    build: ./hmi
    container_name: hmi
    depends_on:
      - backend
    ports:
      - '4200:4200'

  backend:
    build:
      context: ./backend/app
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: backend
    depends_on:
      - db
      - keycloak
      - chirpstack
      - chirpstack-gateway-bridge
      - chirpstack-rest-api
      - nodered
      - influxdb
    ports:
      - '8080:8080'

  keycloak:
    image: keycloak/keycloak:25.0.2
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db:3306/keycloak_db
      KC_DB_USERNAME: dilss
      KC_DB_PASSWORD: Orion@99
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - './keycloak/themes/mirriga/:/opt/keycloak/themes/mirriga/'
    ports:
      - '8081:8080'
    command: start-dev
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3306:3306'

  nodered:
    image: nodered/node-red
    container_name: nodered
    volumes:
      - ./node_data:/data
    ports:
      - '1880:1880'

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dilss
      - DOCKER_INFLUXDB_INIT_PASSWORD=Orion@99
      - DOCKER_INFLUXDB_INIT_ORG=mirriga-corp
      - DOCKER_INFLUXDB_INIT_BUCKET=mirriga
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=MyInitialAdminToken0==
    volumes:
      - ./influxdb_data:/var/lib/influxdb2:rw
    ports:
      - '8086:8086'
volumes:
  data:
