create table agricultural_crops (water_availability_factor float(53) not null, cicle_duration_days bigint not null, created_at datetime(6) not null, duration_percentage_phase_four bigint not null, duration_percentage_phase_one bigint not null, duration_percentage_phase_three bigint not null, duration_percentage_phase_two bigint not null, id bigint not null, root_depth_cm bigint not null, name varchar(100) not null, primary key (id)) engine=InnoDB;
create table agricultural_crops_SEQ (next_val bigint) engine=InnoDB;
insert into agricultural_crops_SEQ values ( 1 );
create table areas (created_at datetime(6) not null, id bigint not null, soil_id bigint, name varchar(100) not null, primary key (id)) engine=InnoDB;
create table areas_SEQ (next_val bigint) engine=InnoDB;
insert into areas_SEQ values ( 1 );
create table coordinates (latitude decimal(21,18) not null, longitude decimal(21,18) not null, area_id bigint not null, created_at datetime(6) not null, node_order bigint not null, primary key (area_id, node_order)) engine=InnoDB;
create table irrigation_systems (efficiency float(53) not null, created_at datetime(6) not null, flow_rate bigint not null, id bigint not null, category varchar(100) not null, name varchar(100) not null, type varchar(100) not null, primary key (id)) engine=InnoDB;
create table irrigation_systems_SEQ (next_val bigint) engine=InnoDB;
insert into irrigation_systems_SEQ values ( 1 );
create table soil (cc float(23) not null, density float(23) not null, pmp float(23) not null, created_at datetime(6) not null, id bigint not null, name varchar(100) not null, primary key (id)) engine=InnoDB;
create table soil_SEQ (next_val bigint) engine=InnoDB;
insert into soil_SEQ values ( 1 );
alter table areas add constraint FKb2u2c65a2d9sk2i3424ekcp3f foreign key (soil_id) references soil (id);
alter table coordinates add constraint FK2frw33nj716h51lchwga63yqy foreign key (area_id) references areas (id);
