alter table areas drop foreign key FKb2u2c65a2d9sk2i3424ekcp3f;
alter table coordinates drop foreign key FK2frw33nj716h51lchwga63yqy;
drop table if exists agricultural_crops;
drop table if exists agricultural_crops_SEQ;
drop table if exists areas;
drop table if exists areas_SEQ;
drop table if exists coordinates;
drop table if exists irrigation_systems;
drop table if exists irrigation_systems_SEQ;
drop table if exists soil;
drop table if exists soil_SEQ;
